# -*- coding: utf-8 -*-
"""py_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4iHIFM1TQZFPC3udIJ6vT40u8wEbC2T
"""

import numpy

list = [1.6, 'abc',4]
print(list)

#unordered list
list = [10, 30, 20, 40]
print(list)

"""# list operations

**Concatenation**
"""

a = [1, 2, 3]
b = [5, 6, 7]
c = a + b
print(c)

"""**repeatation**"""

a = [0] * 5
print(a)

"""**slicing**"""

a = [1,2,3,4,5,6,7]
print(a[1:3])
print(a[-4:-2])
print(a[-1:-3])
print(a[:5])
print(a[4:])
print(a[:])
print(a)

"""**assignement**"""

age = [18, 19, 20, 16]
hrs_studied = [5, 6, 4, 3.5]
marks =

"""**list cloning**"""

a = [1, 'vivek', 2, 'hari']
b = a[:]
print(b)